code reorganized
htmlacademy-javascript/2115357-keksobooking-26 pull request #17
Opened 2022-06-26 05:38 UTC by sbbs8668

2022-07-07 17:36 UTC, iksah requested changes
В целом все очень хорошо. Решение не стандартное, и это не минус а плюс. У тебя достаточно интересный декларативный подход, и думаю тебе мог бы очень понравиться Webpack (это инструмент для сборки приложений).
Наша главная задача сейчас будет причесать и по возможности упростить твое приложение, чтобы с ним было легче работать.

Для начала давай пройдемся по уже написанным комментариям - не стесняйся спрашивать и уточнять если где-то что-то не понятно или если с чем то не согласен.

Так же хочу обратить внимание на размер файлов - сейчас они зачастую очень большие. Я рекомендую попробовать разделить файлы на файлики поменьше - целиться в длину 80-140 строк (и не стоит экономить, большое количество файлов это не проблема). Иногда размер файла может вылезать за эти рамки, но это нужно смотреть по ситуации уже.

2022-07-07 17:36 UTC, iksah commented on js/dom-class.js
> +import   { getLocalText }                 from './functions/normalize-card-template.js';
Обычно так не форматируют - пробел до скобки, пробел после и все.

2022-07-07 17:36 UTC, iksah commented on js/dom-class.js
> +  0: [0, 100000], /*for 'any' value*/
Общая рекомендация по написанию комментариев:
Обычно в`/* some code */` оборачивают куски кода
Обычные комментарии отбивают `// comment`
А документацию функций/классов отбивают через [Javadoc](https://en.wikipedia.org/wiki/Javadoc)
```
/** Description of function
 * some arguments etc.
 */
```

2022-07-07 17:36 UTC, iksah commented on js/dom-class.js
> +  0: [0, 100000], /*for 'any' value*/
Так же, по идее это не перечисление а словарик, можно назвать с маленькой буквы было.

2022-07-07 17:36 UTC, iksah commented on js/dom-class.js
> +];
Вот эти списки - точно не перечисление и не пройдет по критерию о именовании.
1) Я бы рекомендовал убрать toSet и оставить просто elementAttributes (обычно последнее слово в названии описывает что это - это атрибуты, и поскольку множественное число, то это список атрибутов.
2) Ну и назвать с маленькой буквы

2022-07-07 17:36 UTC, iksah commented on js/dom-class.js
> +  [30, 'minlength'],
Можно не переделывать, но я бы рекомендовал работать с аттрибутами через объекты:
`[{name: 'minlength', value: '20'}, ...]`. Так будет проще в случае чего расширить функциональность и проще читать код.

2022-07-07 17:36 UTC, iksah commented on js/dom-class.js
> +class DomClass {
стоит назвать как-нибудь ближе к бизнес логике, иначе кажется что это универсальный механизм который можно переиспользовать в других местах. Я бы переименовал во что-то типа KeksobuckingApp например

2022-07-07 17:36 UTC, iksah commented on js/dom-class.js
> +    this.Children = {
Здесь с маленькой буквы, потому что это не перечисление

2022-07-07 17:36 UTC, iksah commented on js/dom-class.js
> +    this.Containers = {
тоже с маленькой буквы

2022-07-07 17:36 UTC, iksah commented on js/dom-class.js
> +    this.Templates = {
И здесь маленькая буква.

2022-07-07 17:36 UTC, iksah commented on js/dom-class.js
> +    this.Classes = {
так же, маленькая буква

2022-07-07 17:36 UTC, iksah commented on js/dom-class.js
> +        classTo: 'ad-form__element',
Тут тоже с именованием надо поработать. Сейчас получается тавтология:
**class**es.pristine**Class**.**class**To - мы три раза повторяем слово class хотя уже обозначили что здесь все классы. Предлагаю оставить класс только в корне, а дальше просто оставить типы, чтоб было `classes.pristine.to` (и с другими классами так же)

2022-07-07 17:36 UTC, iksah commented on js/dom-class.js
> +      sliderClass: 'slider__container',
Здесь тоже классы можно опустить из названия

2022-07-07 17:36 UTC, iksah commented on js/dom-class.js
> +    return document.querySelector(this.Containers[containerName].selectorValue);
1) давай здесь переиспользуем getContainer
2) что будет, если `this.Containers[containerName]` вернет `undefined` (т.е. функцию вызовут с некорректным именем контейнера)?

2022-07-07 17:36 UTC, iksah commented on js/dom-class.js
> +    return this.Classes[className] || false;
А зачем false? Нельзя обойтись undefined?

2022-07-07 17:36 UTC, iksah commented on js/dom-class.js
> +  switch (params[0]) {
1) Я бы рекомендовал вынести каждый кейс в отдельную функцию и вызывать по месту отдельно каждую из этих функций.
2) Если хочется здесь использовать общий сервис/функцию - или сделать объект с методами, или вынести каждый из кейсов в переменную (чтобы строка например `fillContainerWithTemplate` была в константе, и её можно было переиспользовать)

2022-07-07 17:36 UTC, iksah commented on js/fetch-api.js
>    const PARAMETERS = {
PARAMETERS используется только в этом файле, а значит его можно опустить. Используй прямо константы

2022-07-07 17:36 UTC, iksah commented on js/fetch-api.js
>    whatToDo = 'pull',
Вместо этого лучше или сделать две отдельные функции (а общую часть вынести в третью функцию например), или сделать объект с методами api {pull, push}

2022-07-07 17:36 UTC, iksah commented on js/functions/fill-container-with-template.js
> +      else if (bridge === 'avatar') {
Вот эти if-else стоит переписать на switch-case, плюс можно вынести код внутри в отдельные функции - так будет проще читать и поддерживать код.

2022-07-07 17:36 UTC, iksah commented on js/functions/fill-container-with-template.js
> +      Object.assign(data, dataOriginal);
Для success и error обработка одинаковая, можно объединить.

2022-07-07 17:36 UTC, iksah commented on js/functions/form-state-toggle.js
> +/* enable: domProcessor(false, 'mapFilterEnable') */
Не совсем понятно что это ха комментарии

2022-07-07 17:36 UTC, iksah commented on js/functions/form-state-toggle.js
> +const FieldsToToggle = [
Тоже с маленькой буквы можно назвать

2022-07-07 17:36 UTC, iksah commented on js/functions/form-state-toggle.js
> +const FieldsToToggle = [
И лучше toggleableFields (1 слово описывает что это можно тогглить, а второе - что это список филдов)

2022-07-07 17:36 UTC, iksah commented on js/functions/normalize-card-template.js
> +      switch (true) {
А почему не switch(data.offer.rooms) {...} ?
Текущий вариант очень нестандартен :)

2022-07-07 17:36 UTC, iksah commented on js/functions/normalize-card-template.js
> +const LolcalTexts = {
Lo**l**calTexts => LocalTexts

2022-07-07 17:36 UTC, iksah commented on js/functions/normalize-card-template.js
> +      data.templates[templateNickName] = {};
для простоты можно все свойства сразу внести в объект

2022-07-07 17:36 UTC, iksah commented on js/functions/normalize-card-template.js
> +      data.templates[templateNickName].features = data.offer.features && data.offer.features.length && data.offer.features || '';
features кажется должно быть списком, а в конце заменяется на строку

2022-07-07 17:36 UTC, iksah commented on js/map-and-filter-form.js
> +processDomClass(false, 'mapFilterDisable');
Было бы проще если б было две функции, например:
disablePage();
disableMapFilter();

2022-07-07 17:36 UTC, iksah commented on js/map-and-filter-form.js
> +  2: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
вместо 1 и 2 лучше написать говорящие имена, что именно эти апарметры значат

2022-07-07 17:36 UTC, iksah commented on js/map-and-filter-form.js
> +const SimilarAdsAdditional = {
вот здесь не понятно - что за Additional. Надо уточнить

2022-07-07 17:36 UTC, iksah commented on js/map-and-filter-form.js
> +    if (property === FEATURES_FIELD_NAME) {
Сейчас все проверки будут совершаться вне зависимости орт того, что одна из них могла быть успешной. Лучше переделать на switch-case

2022-07-07 17:36 UTC, iksah commented on js/map-and-filter-form.js
> +  });
Вместо промисе лучше подпишись на событие load карты (https://leafletjs.com/reference.html#map-load) Иначе например карта будет долго прогружаться - приложение не заработает как надо

2022-07-07 17:36 UTC, iksah commented on js/map-and-filter-form.js
> +      processDomClass(false, 'mapFilterEnable');
Сейчас внутри try блока очень много кода6 и потребуется больше времени в случае ошибки. Лучше вынести вне блока все то, для чего проверка не требуется. Если здесь мы хотим только поймать ошибки в api, то внутри try лучше оставить только вызов api.

2022-07-07 17:36 UTC, iksah commented on js/validate-ad-form.js
> +const sendNewAdToApi = () => {
Api - это описание метода взимодейтсвия между клиентом и сервером. Отправляем данные мы на сервер, так что sendNewAdToServer (или можно просто createAd).

2022-07-07 17:36 UTC, iksah commented on js/validate-ad-form.js
> +  formSubmitButtonToggle(false);
formSubmitButtonToggle читается как функция которая устанавливает противоположное значение. Лучше будет disableFormSubmitButton и enableFormSubmitButton

2022-07-07 17:36 UTC, iksah commented on js/validate-ad-form.js
> +    /*setTimeout - formReset removes values slower*/
Было бы лучше там где вызывается ресет формы и сделать таймер. Потому что без ресета и таймер не нужен.

2022-07-07 17:36 UTC, iksah commented on js/validate-ad-form.js
> +    for (const index in AdFormChildren) {
fot (const childData of adFormChildren} {...}

2022-07-07 17:36 UTC, iksah commented on js/validate-ad-form.js
> +        ChildData.attributesToSet.forEach((value0Property1) => {
Здесь кажется можно воспользоваться https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

2022-07-07 17:36 UTC, iksah commented on js/validate-ad-form.js
> +      if (typeof ChildData.objectToValidate !== 'undefined') {
просто `if (ChildData.objectToValidate) {...}` А то вдргу там null?

2022-07-07 17:36 UTC, iksah commented on js/validate-ad-form.js
> +        const ObjectToValidate = AdForm.children[ChildData.objectToValidate.name];
все с маленькой буквы

2022-07-07 17:36 UTC, iksah commented on js/validate-ad-form.js
> +        switch (index) {
Ага, вижу, получается это не index а key (это к комменту выше)

2022-07-07 17:36 UTC, iksah commented on js/validate-ad-form.js
> +    for (const index in AdFormChildren) {
так, кажется тут должен быть key а не index (index всегда число, и обычно применяется в разговоре о списках, а не объектах)

2022-07-08 08:37 UTC, sb-3455261 commented on js/dom-class.js
> +    return document.querySelector(this.Containers[containerName].selectorValue);
1. getContainerNode убрал полностью

2. Не вернет, это базовый конфиг. 
Задается вручную и не перезадается при использовании (т.е. функцию вызовут - она не вызывается отдельно).
Оно не будет вообще изначально работать если этот конфиг задан неверно.

2022-07-08 08:43 UTC, sbbs8668 commented on js/dom-class.js
> +  0: [0, 100000], /*for 'any' value*/
Ты бы не мог, пожалуйста, объяснить, или пару примеров, что такое "словарь", "перечисление".
В теории вроде как нигде об этом не было.

Не происходи ли это случайно из Java?
Вроде как в JS нигде такого нет..

2022-07-08 08:45 UTC, sbbs8668 commented on js/dom-class.js
> +        classTo: 'ad-form__element',
Это встроенное от пристина, переделал максимально.

2022-07-08 08:55 UTC, sbbs8668 commented on js/dom-class.js
> +    return this.Classes[className] || false;
Тут в принципе эта проверка излишняя, так как динамически оно не вызывается и прописывается как конфиг изначально вручную.

2022-07-08 09:12 UTC, sbbs8668 commented on js/dom-class.js
> +  switch (params[0]) {
Тут происходит своего рода связка между классом DomClass (уже переименован) и экстерним окружением. При этом сам этот класс из модуля не выводится.
А функция processDomClass (переименована) как бы транслирует DomClassу что от него нужно экстерниму окружению. Такое мини api.
Если это переделать, то придется экспортировать объект, функции итд. и в принципе все бы было по другому.

А сами инструкции типа fillContainerWithTemplate прописываются по месту вызова, можно и в константе и как угодно.

В комментарии в каждом case: написано как это вызвать, например
    case 'getClass':
      /* COMMAND: domClass(false, 'getClass', className); */

возможно такое решение?

2022-07-08 09:16 UTC, sbbs8668 commented on js/fetch-api.js
>    const PARAMETERS = {
Оно там динамически изменяется в зависимости от того что это пуш/пул и без этого не будет работать.

2022-07-08 13:56 UTC, sbbs8668 commented on js/functions/form-state-toggle.js
> +/* enable: domProcessor(false, 'mapFilterEnable') */
это как раз что надо послать на "мини api"

2022-07-08 14:02 UTC, sb-3455261 commented on js/functions/form-state-toggle.js
> +const FieldsToToggle = [
я думаю FieldsToToggle подходит больше чем toggleableFields 
здесь мы не делаем переключаемыми (toggleable) поля (Fields)
а перечисляем поля (Fields) предназначенные (To) к переключению (Toggle) состояния

2022-07-08 14:09 UTC, sbbs8668 commented on js/functions/normalize-card-template.js
> +      switch (true) {
Там идет сравнение числовых значений для подбора склонения слов.
Больше меньше итд, и срабатывает именно там где сравнение дает тру.

Если сделать switch(data.offer.rooms) то оно не будет сравниваться а будет проскакивать любое значение.

Примерно:
switch(true) {
case a === 1 : { a();}
case a < 1: {b();}
case a > 1: {c();}
}

а по другому не знаю как в свиче сравнить, тогда только свич убирать

2022-07-08 14:10 UTC, sbbs8668 commented on js/functions/normalize-card-template.js
> +      switch (true) {
но он тут как раз к месту

2022-07-08 14:24 UTC, sbbs8668 commented on js/functions/normalize-card-template.js
> +      data.templates[templateNickName].features = data.offer.features && data.offer.features.length && data.offer.features || '';
оно в итоге на пустоту проверяется в любом случае, но для соответствия типу данных да

и доп.вопрос, ты "списком" массивы называешь?

2022-07-08 14:25 UTC, sb-3455261 commented on js/map-and-filter-form.js
> +processDomClass(false, 'mapFilterDisable');
они делают одно и тоже абсолютно и поэтому вместе

2022-07-08 14:39 UTC, sbbs8668 commented on js/map-and-filter-form.js
> +  2: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
это родные параметры
как то не получилось найти где бы конкретно описывалось что это именно

2022-07-08 17:25 UTC, sbbs8668 commented on js/validate-ad-form.js
> +      if (typeof ChildData.objectToValidate !== 'undefined') {
здесь тоже предустановленное значение, оно не динамическое, 
оно или есть и код выполняется
или неопределено и код идет дальше

2022-07-08 19:16 UTC, sbbs8668 commented on js/map-and-filter-form.js
> +  });
Я промисы убрал и кстати с ними все работало четко.
С этим родным событием не понятно что происходит.

Вызывается оно теперь так:
....map = L
    .map(container.selector.replace('#',''))
    .on('load', () => {
      /*set initial address field value in adForm*/
      recordAdAddressFromMap({lat: container.initialLat, lng: container.initialLng}, true);
      processTheMap();
    })
    .setView({ ....

и по идее внутри функции processTheMap() уже должна быть полностью инициализированная map и все остальное что к ней относится.
Но оно не так, переменная map при запуске processTheMap() из этого места внутри processTheMap() еще не существует.
Я ее изначально изза этого поставил на прмис потому что не понятно как оно работает или я что-то не понимаю.
Если сможешь объяснить в чем тут дело будет круто))

2022-07-12 06:56 UTC, merged